### ISSUE TITLE
getting this issue in windows

### ISSUE THREAD

**Issue by rajkumarks7** [robotn/gohook#17]
when i am using your library i am getting these error suddenly 
i am getting this issue in windows10 64 bit can you help me this one
win_hook_event_proc [650]: setWindowsHookEx() failed! (0X486)

**Comment by rajkumarks7** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/64638741/86202348-9b5c9c80-bb7f-11ea-8cfe-866621b4e033.png)

**Comment by dbv** [comment]
replace (
    github.com/robotn/gohook => github.com/robotn/gohook v0.30.1
)

用老版本可以解决 use old version to slove

**Comment by rk40953** [comment]
Hey thank you for the help of it is solved I will close the issue.

**Comment by rajkumarks7** [comment]
> replace (
> github.com/robotn/gohook => github.com/robotn/gohook v0.30.1
> )
> 
> 用老版本可以解决 use old version to slove

i am not getting this version
package github.com/robotn/gohook v0.30.1/...: github.com/robotn/gohook v0.30.1/...: invalid import path: malformed import path "github.com/robotn/gohook v0.30.1": invalid char ' '
github.com/robotn/gohookv0.30.1 (download)


i tried removing the space

# cd .; git clone -- https://github.com/robotn/gohookv0.30.1 C:\Users\kottur\go\src\github.com\robotn\gohookv0.30.1
Cloning into 'C:\Users\kottur\go\src\github.com\robotn\gohookv0.30.1'...
remote: Repository not found.
fatal: repository 'https://github.com/robotn/gohookv0.30.1/' not found
package github.com/robotn/gohookv0.30.1/...: exit status 128

**Comment by rajkumarks7** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/64638741/86754643-aa9b8880-c05e-11ea-9830-8fad1bc38fda.png)

**Comment by rajkumarks7** [comment]
> replace (
> github.com/robotn/gohook => github.com/robotn/gohook v0.30.1
> )
> 
> 用老版本可以解决 use old version to slove

getting same error after running for sometime i changed the version of the library like you told me but getting same error after running for sometime. like i got the same error before in version 0.30.3

**Comment by vcaesar** [comment]
I tested it on win7 and can't reproduce it, I will be test on win10.

**Comment by rajkumarks7** [comment]
Thank you

**Comment by rajkumarks7** [comment]
> I tested it on win7 and can't reproduce it, I will be test on win10.

did you test it in windows 10 ?

**Comment by rajkumarks7** [comment]
thank you for helping me solved above error
