### ISSUE TITLE
Example in README is wrong.

### ISSUE THREAD

**Issue by pinpox** [robotn/gohook#22]
Hi, just a quick hint: The example in the `README.md` does not work.

The import should probably be:
```go
	hook "github.com/robotn/gohook"
```
instead of just:
```go
	 "github.com/robotn/gohook"
```

EDIT: I just saw there is a `examples/main.go` file, with the correct code, but I can't get it to work as expected. Could you help me out? I modified it like this (just to add more visible output):
```go
package main

import (
	"fmt"

	hook "github.com/robotn/gohook"
)

func addEvent() {
	fmt.Println("--- Please press ctrl + shift + q to stop hook ---")
	hook.Register(hook.KeyDown, []string{"q", "ctrl", "shift"}, func(e hook.Event) {
		fmt.Println("ctrl-shift-q")
		hook.End()
	})

	fmt.Println("--- Please press w---")
	hook.Register(hook.KeyDown, []string{"w"}, func(e hook.Event) {
		fmt.Println("wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww")
	})

	s := hook.Start()
	<-hook.Process(s)
}

// hook listen and return values using detailed examples
func add() {
	fmt.Println("hook add...")
	s := hook.Start()
	defer hook.End()

	ct := false
	for {
		i := <-s

		if i.Kind == hook.KeyHold && i.Rawcode == 59 {
			ct = true
		}

		if ct && i.Rawcode == 12 {
			break
		}
	}
}

// base hook example
func base() {
	fmt.Println("hook start...")
	evChan := hook.Start()
	defer hook.End()

	for ev := range evChan {
		fmt.Println("hook: ", ev)
	}
}

func main() {
	addEvent()

	base()

	add()
}
```
The application runs, but whatever I do or press, I can't manage to print out the `wwwwwwwwwwwwwwwwwwwwwwww` string. What is  supposed to happen? Also, `ctrl`+`shift`+`q` isn't doing anything either. Here is my output as I press `w` a few times, then random other keys and lastly `ctrl`+`shift`+`q` and `ctrl+c` to quit:
[![asciicast](https://asciinema.org/a/S3ybknPlzeYwtE3a4bkN4mHg8.svg)](https://asciinema.org/a/S3ybknPlzeYwtE3a4bkN4mHg8)

**Comment by cauefcr** [comment]
Thanks!

**Comment by vcaesar** [comment]
Closed because of new version and time long.
