### ISSUE TITLE
How do I register function keys?

### ISSUE THREAD

**Issue by vs-123** [robotn/gohook#25]
Hi, I tried to register F6 by using this code
```go
fmt.Println("Press F6")
hook.Register(hook.KeyDown, []string{"f6"}, func(e hook.Event) {
		fmt.Println("F6 was pressed")
})
s := hook.Start()
<-hook.Process(s)
```
but it doesn't seem to work.

My question is, how do I register function keys? Thank you in advance.

**Comment by cauefcr** [comment]
i've found no realiable way to do that yet.

feel free to PR.
