### ISSUE TITLE
How do I approach the keyboard tab to know the click status?

### ISSUE THREAD

**Issue by buYoung** [robotn/gohook#9]
s := hook.Start()
		defer hook.End()
		for {
			select {
			case i:= <- s :
				fmt.Printf("%s \n", i)
                }

I wrote it like the above code and proceeded with the test.
The only result I want is HOLD or DOWN while I'm pressing TAB, But I've seen that UP/DOWN//HOLD is constantly output.

How do I solve this problem?

**Comment by cauefcr** [comment]
You could use a boolean, when tab is pressed set it to true, when tab is let go set it to false, and use that boolean for your interest.

**Comment by vcaesar** [comment]
Can give me a PR? Thx.

**Comment by cauefcr** [comment]
Even if it's not backwards compatible?

**Comment by buYoung** [comment]
Oh, I was mistaken. While I was pressing the TAB key, I thought that the HOLD and DOWN were continuously output, and the UP was also output.

EXAPLE) 
s := hook.Start()
	defer hook.End()
	d := false
	for {
		select {
		case i := <-s:
			if i.Rawcode == 9 {
				switch i.Kind {
				case 3,4:
					d = true
				case 5:
					d= false
				}
			}
		}
		println(d)
	}
